In [87]:
import cv2 as cv
import numpy as np
from matplotlib import pyplot as plt
img_path = 'SAMSUNG SM-J710F (000014600640).jpg'
imS = cv.imread(img_path, cv.IMREAD_COLOR)
image = cv.resize(imS, (960, 540))

In [88]:
px = imS[530, 959]
print( px )
# imS[100,100] = [255,255,255]
# imS[80:280, 150:330] = [255, 255, 0]
# print( imS[100,100] )

[175 134 101]


In [96]:
# cv.imshow(img_path, imS)
# k = cv.waitKey(0)
hsv = cv.cvtColor(imS, cv.COLOR_BGR2HSV)
px = hsv[530, 959]
print( px )
low_grey = np.array([0, 0, 127])
high_grey = np.array([0, 0, 129])
mask = cv.inRange(hsv, low_grey, high_grey)
# res = cv.bitwise_or(imS,imS, mask= mask)
# cv.imshow(img_path, res)
# k = cv.waitKey(0)
# cv.imshow(img_path, mask)
# k = cv.waitKey(0)

rgb_mask=cv.cvtColor(mask,cv.COLOR_GRAY2BGR)#change mask to a 3 channel image
mask_out = cv.subtract(imS, rgb_mask)
# cv.imshow(img_path, mask_out)
# k = cv.waitKey(0)


mask_out_grey = cv.cvtColor(mask_out, cv.COLOR_BGR2GRAY)
_,thresh = cv.threshold(mask_out_grey,1,255,cv.THRESH_BINARY)
# cv.imshow(img_path, thresh)
# k = cv.waitKey(0)
contours,hierarchy = cv.findContours(thresh,cv.RETR_EXTERNAL,cv.CHAIN_APPROX_SIMPLE)
cnt = contours[0]
print(contours[0])
x,y,w,h = cv.boundingRect(cnt)
print('x,y,w,h')
print(x)
print(y)
print(w)
print(h)
crop = imS[y:y+h,x:x+w]
# cv.imshow(img_path, crop)
# k = cv.waitKey(0)
cv.imwrite('softwines.png', crop)

[107 108 175]
[[[   0    0]]

 [[   0 2791]]

 [[2239 2791]]

 [[2239 2784]]

 [[2240 2783]]

 [[3123 2783]]

 [[3124 2782]]

 [[3125 2783]]

 [[4127 2783]]

 [[4127 2380]]

 [[4126 2379]]

 [[4127 2378]]

 [[4127 2153]]

 [[4126 2152]]

 [[4127 2151]]

 [[4127    0]]]
x,y,w,h
0
0
4128
2792


True

In [90]:
# rgb_img = cv.cvtColor(imS, cv.COLOR_BGR2RGB)
# hsv_img = cv.cvtColor(rgb_img, cv.COLOR_RGB2HSV)
# gray_img = cv.cvtColor(imS, cv.COLOR_RGB2GRAY)
# light_grey = (0, 0, 127)
# dark_grey = (1, 1, 130)
# # mask = cv.inRange(hsv_img, light_grey, dark_grey)
# px = hsv_img[530, 959]
# print( px )
# # result = cv.bitwise_xor(imS, imS, mask=mask)
# cv.imshow(img_path, hsv_img)
# cv.imshow(img_path, gray_img)
# k = cv.waitKey(0)
# z=0
# for x in range(539):
#     for y in range(1):
#         if (gray_img[x, y] == gray_img[x, y+100] == gray_img[x, y+200]):
#             z=z+1
#             print(z)
#
# cv.line(imS, (0,540-z), (960, 540-z), (0, 0, 0), 2)
# # cv.line(imS, (0,0), (540,960), (255, 0, 0), 5)
#
# cv.imshow(img_path, imS)
# k = cv.waitKey(0)
# # if (gray_img[531, 959] == gray_img[530, 959]):
# #     print('same Value in pic')


In [91]:
# bitwise_xor
# cropped_image = image[0:3096, 0:4128]

print( imS.shape )
print( image.shape )
print( image.size )
print( image.dtype )

(3096, 4128, 3)
(540, 960, 3)
1555200
uint8


In [92]:
# cv.imshow(img_path, imS)
# cv.imshow("Cropped Image", cropped_image);
# k = cv.waitKey(0)